app:
  replicaCount: 1
  # replicaCount: 2
  serviceAccount:
    create: true
  automountServiceAccountToken: true
  env:
    - name: APP_ENV
      value: "production"
  resources:
    requests:
      cpu: "200m"
      memory: "256Mi"
    limits:
      cpu: "1000m"
      memory: "512Mi"
  hpa:
    enabled: false
    # NOTE: because application does not support scaling with replicas, disable them
    # enabled: true
    # minReplicas: 2
    # maxReplicas: 6
    # targetCPUUtilizationPercentage: 50
    # targetMemoryUtilizationPercentage: 80
  configMaps:
    - name: config
      data:
        config.yaml:
          listen_addr: ":8080"
          environment: "production"
          version: "production"
          logger:
            level: "info"
            metadata:
              service: "terraform-parse-service"
              env: "production"
          tracing:
            exporter: "otlp_grpc"
            endpoint: "tempo.monitoring.svc.cluster.local:4317"
            insecure: false
            sample_ratio: 1.0
          metrics:
            addr: ":9091"
          providers:
            aws:
              templates_dir: "/templates/aws"
              storage_dir: "/output/aws"

gateway:
  istio:
    virtualService:
      hosts:
        - "terraform-parse-service.example.com"
    destinationRule:
      enabled: true
      host: '{{ .Release.Name }}'

tfTemplates:
  - aws/s3/bucket.tf.tmpl
