app:
  replicaCount: 1

  image:
    repository: terraform-parse-service
    tag: "0.1.0"
    pullPolicy: IfNotPresent

  serviceAccount:
    create: true

  automountServiceAccountToken: true

  env:
    - name: APP_ENV
      value: "production"

  resources:
    requests:
      cpu: "200m"
      memory: "256Mi"
    limits:
      cpu: "1000m"
      memory: "512Mi"

  hpa:
    enabled: false
    # NOTE: because application does not support scaling with replicas, disable them
    # enabled: true
    # minReplicas: 2
    # maxReplicas: 6
    # targetCPUUtilizationPercentage: 50
    # targetMemoryUtilizationPercentage: 80

  configMaps:
    - name: config
      data:
        config.yaml:
          listen_addr: ":8080"
          service_name: "terraform-parse-service"
          environment: "production"
          version: '{{ .Values.image.tag }}'
          logger:
            level: "info"
          tracing:
            exporter: "otlp_grpc"
            endpoint: "alloy.monitoring.svc.cluster.local:4317"
            insecure: true
            sample_ratio: 1.0
          metrics:
            addr: ":9091"
          providers:
            aws:
              templates_dir: "/templates/aws"
              templates_poll_interval: "5s"
              storage_dir: "/output/aws"

gateway:
  istio:
    virtualService:
      hosts:
        - "terraform-parse-service.example.com"
    destinationRule:
      enabled: true
      host: '{{ .Release.Name }}'

tfTemplates:
  - aws/s3/bucket.tf.tmpl
