app:
  replicaCount: 1
  serviceAccount:
    create: true
  automountServiceAccountToken: true
  env:
    - name: OTEL_SERVICE_NAME
      value: "terraform-parse-service"
    - name: OTEL_RESOURCE_ATTRIBUTES
      value: 'deployment.environment.name=dev,service.version={{ .Values.image.tag }}'
    - name: OTEL_TRACES_EXPORTER
      value: "none"
  hpa:
    enabled: false
    # NOTE: because application does not support scaling with replicas, disable them
  configMaps:
    - name: config
      data:
        config.yaml:
          listen_addr: ":8080"
          service_name: "terraform-parse-service"
          environment: "dev"
          version: '{{ .Values.image.tag }}'
          logger:
            level: "debug"
          metrics:
            addr: ":9091"
          providers:
            aws:
              templates_dir: "/templates/aws"
              templates_poll_interval: "5s"
              storage_dir: "/output/aws"

gateway:
  istio:
    gateway:
      hosts:
        - "terraform-parse-service.dev.example.com"
    virtualService:
      hosts:
        - "terraform-parse-service.dev.example.com"

tfTemplates:
  - aws/s3/bucket.tf.tmpl
