istio:
  enabled: false

  gateway:
    create: false
    name: ""
    port: 80
    hosts:
      - "*"

  virtualService:
    enabled: false
    hosts: []
    routes: []

  destinationRule:
    enabled: false
    host: ""
    trafficPolicy: {}
