{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "terraform.fullname" . }}-sidecar
  labels:
    {{- include "terraform.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "terraform.fullname" . }}-sidecar
subjects:
  - kind: ServiceAccount
    name: {{ if .Values.app.serviceAccount.create }}{{ default (include "terraform.fullname" .) .Values.app.serviceAccount.name }}{{ else }}{{ default "default" .Values.app.serviceAccount.name }}{{ end }}
    namespace: {{ .Release.Namespace }}
{{- end }}
