{{- if and .Values.istio.enabled .Values.istio.gateway.create }}
apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: {{ include "gateway.fullname" . }}
  labels:
    {{- include "gateway.labels" . | nindent 4 }}
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: {{ .Values.istio.gateway.port }}
        name: http
        protocol: HTTP
      hosts:
        {{- toYaml .Values.istio.gateway.hosts | nindent 8 }}
{{- end }}
