grafana.ini:
  auth.anonymous:
    enabled: true
    org_role: Admin

persistence:
  enabled: false

dashboardProviders:
  dashboardproviders.yaml:
    apiVersion: 1
    providers:
      - name: terraform-parse-service
        orgId: 1
        folder: Terraform Parse Service
        type: file
        disableDeletion: false
        editable: true
        options:
          path: /var/lib/grafana/dashboards/terraform-parse-service

dashboardsConfigMaps:
  terraform-parse-service: grafana-dashboard-terraform-parse-service

datasources:
  datasources.yaml:
    apiVersion: 1
    datasources:
      - name: Tempo
        type: tempo
        access: proxy
        url: http://tempo.monitoring.svc.cluster.local:3200
        uid: tempo
        isDefault: false
        jsonData:
          tracesToLogsV2:
            datasourceUid: loki
            filterByTraceID: true
            spanStartTimeShift: "-5m"
            spanEndTimeShift: "5m"
          serviceMap:
            datasourceUid: prometheus
          nodeGraph:
            enabled: true

      - name: Loki
        type: loki
        access: proxy
        url: http://loki.monitoring.svc.cluster.local:3100
        uid: loki
        isDefault: false
        jsonData:
          derivedFields:
            - name: TraceID
              matcherRegex: '"trace_id":"([a-f0-9]+)"'
              url: "$${__value.raw}"
              datasourceUid: tempo

      - name: Prometheus
        type: prometheus
        access: proxy
        url: http://prometheus-server.monitoring.svc.cluster.local
        uid: prometheus
        isDefault: true
