listen_addr: ":8080"
environment: "development"
version: "dev"
logger:
  level: "info"
tracing:
  exporter: "stdout"
  endpoint: "localhost:4317"
  sample_ratio: 1.0
metrics:
  addr: ":9091"
providers:
  aws:
    templates_dir: "./templates/aws"
    storage_dir: "./output/aws"
