listen_addr: ":8080"
service_name: "terraform-parse-service"
environment: "${ENVIRONMENT:development}"
version: "${VERSION:dev}"
logger:
  level: "info"
metrics:
  addr: ":9091"
providers:
  aws:
    templates_dir: "./templates/aws"
    templates_poll_interval: "5s"
    storage_dir: "./output/aws"
