listen_addr: ":8080"
environment: "production"
version: "dev"
logger:
  level: "info"
tracing:
  exporter: "otlp_grpc"
  endpoint: "alloy:4317"
  insecure: true
  sample_ratio: 1.0
metrics:
  addr: ":9091"
providers:
  aws:
    templates_dir: "/templates/aws"
    storage_dir: "/output/aws"
