listen_addr: ":8080"
logger:
  level: "info"
  metadata:
    service: "terraform-parse-service"
tracing:
  exporter: "otlp_grpc"
  endpoint: "alloy:4317"
  insecure: true
  sample_ratio: 1.0
providers:
  aws:
    templates_dir: "/templates/aws"
    storage_dir: "/output/aws"
